# Generated by Django 3.0.7 on 2020-06-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tej', '0006_defaultemplate_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateviewArticledefaultemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='defaultemplate',
            new_name='ArchiveArticledefaultemplate',
        ),
    ]
