# Generated by Django 3.0.7 on 2020-06-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tej', '0007_auto_20200625_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivearticledefaultemplate',
            name='pub_date',
        ),
    ]
