# Generated by Django 3.0.7 on 2020-06-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tej', '0010_defaultemplate_updated_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='defaultemplate',
        ),
    ]
