# Generated by Django 3.0.7 on 2020-06-25 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tej', '0011_delete_defaultemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivearticle',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
