# Generated by Django 3.0.7 on 2020-06-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tej', '0012_archivearticle_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivearticle',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
